#!/usr/bin/env bash
# Install nginx
apt -y update
apt -y install nginx
ufw allow 'Nginx HTTP'
chown -R $USER:$USER /var/www/html/
chmod -R 755 /var/www
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
service nginx start
