#!/usr/bin/env bash
# Install nginx
sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/
sudo chmod -R 755 /var/www/
sudo echo "Holberton School" > /var/www/html/index.html
sudo /etc/init.d/nginx start
