#!/usr/bin/env bash
# Install nginx
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html/
sudo chmod -R 755 /var/www
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx start
