#!/usr/bin/env bash
#redirectme
apt-get -y update
apt-get -y install nginx
sed -i "30i \\\trewrite ^/redirect_me  https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx start
