#!/usr/bin/env bash
# Install the load balanecer on lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "
frontend front
	bind *:80
	mode http
	default_backend webservers
backend webservers
    balance roundrobin
    server 1205-web-01  104.196.193.253:80 check
    server 1205-web-02  54.221.57.153:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart