#!/usr/bin/env bash
# listen to port 80 no 8080
sudo sed -i 's/8080/80/g'  /etc/nginx/sites-enabled/default
sudo sed -i 's/8080/80/g'  /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart
