#!/usr/bin/env bash
# Fixing a container to run nginx as nginx user
sudo service apache2 stop
pkill apache2
chmod 644 /etc/nginx/nginx.conf
chown -R nginx /etc/nginx/nginx.conf
su - nginx -c "sed -ie 's/80/8080/g' /etc/nginx/sites-available/default"
su - nginx -c "service nginx restart"
